# Generated by Django 4.2.1 on 2023-06-28 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.problem'),
        ),
        migrations.AlterField(
            model_name='mproblemtype',
            name='problem',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.problem'),
        ),
        migrations.AlterField(
            model_name='mproblemworkbook',
            name='problem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.problem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rec',
            name='problem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.problem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rival',
            name='rival',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='api.boj'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rival',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='challenger', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solved',
            name='problem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.problem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, default='team/default.png', null=True, upload_to='team/%Y/%m/%d'),
        ),
    ]
