# Generated by Django 4.2.1 on 2023-06-17 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mteamuser',
            name='solved',
        ),
    ]
