# Generated by Django 4.2.1 on 2023-06-29 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_board_problem_alter_mproblemtype_problem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.problem'),
        ),
        migrations.CreateModel(
            name='RecRival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.boj')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
