# Generated by Django 4.2.1 on 2023-06-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_board_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='watching',
            field=models.IntegerField(default=0),
        ),
    ]
