# Generated by Django 4.2.1 on 2023-06-27 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_board_updated_at_alter_board_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rival',
            name='rival',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='api.boj'),
        ),
        migrations.AlterField(
            model_name='rival',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenger', to=settings.AUTH_USER_MODEL),
        ),
    ]
