# Generated by Django 4.2.1 on 2023-06-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mworkbookuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbook',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
