# Generated by Django 4.2.1 on 2023-06-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_rec_problem_recrival'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rival',
            old_name='user',
            new_name='follower',
        ),
        migrations.RemoveField(
            model_name='rival',
            name='rival',
        ),
        migrations.AddField(
            model_name='rival',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rival',
            name='ranking',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rival',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rival',
            name='solved_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rival',
            name='streak',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rival',
            name='tier',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
