# Generated by Django 4.2.1 on 2023-06-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_rival_rival_alter_rival_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='ratingAvg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='solveCnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='workbookCnt',
            field=models.IntegerField(default=0),
        ),
    ]
