# Generated by Django 4.2.1 on 2023-06-05 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_problem_team_remove_user_rival_workbook_team_leader_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='problem',
            name='type',
        ),
        migrations.CreateModel(
            name='MProblemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.problem')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.type')),
            ],
        ),
    ]
