# Generated by Django 4.2.1 on 2023-06-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_request_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
