# Generated by Django 4.2.1 on 2023-06-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_mteamuser_is_leader_mteamuser_solved_team_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tier',
            field=models.CharField(default='iron', max_length=10),
        ),
    ]
