# Generated by Django 4.2.1 on 2023-06-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workbook',
            name='title',
            field=models.CharField(default='untitle', max_length=40),
        ),
    ]
